# Generated by Django 6.0 on 2025-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, max_length=1000)),
                ('cover_image', models.URLField(blank=True, max_length=1000)),
                ('is_open', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('min_delivery_time', models.IntegerField(default=15)),
                ('max_delivery_time', models.IntegerField(default=45)),
                ('location', models.JSONField(default=dict)),
                ('owner_user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
