# Generated by Django 6.0 on 2025-12-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('driver_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('AWAITING_ACCEPTANCE', 'AWAITING_ACCEPTANCE'), ('DRIVER_ASSIGNED', 'DRIVER_ASSIGNED'), ('PICKED_UP', 'PICKED_UP'), ('NEARBY', 'NEARBY'), ('ARRIVED', 'ARRIVED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50)),
                ('type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], default='PICKUP', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('delivery_location', models.JSONField(blank=True, null=True)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
